/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/frame2.glb
*/

import React, { useRef, useEffect, useState } from "react";
import { shaderMaterial, useGLTF, useTexture } from "@react-three/drei";
import { extend } from "@react-three/fiber";
import * as THREE from "three";

const FrameMaterial = shaderMaterial(
  {
    uTexture: new THREE.Texture(),
    uFrameSize: new THREE.Vector2(1, 1),
    utextureSize: new THREE.Vector2(1, 1),
  },
  `
    varying vec2 vUv;
    void main() {
      vUv = uv;
      gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
    }
  `,
  `
uniform sampler2D uTexture;
uniform vec2 utextureSize;

varying vec2 vUv;

void main() {
    vec2 centeredUV = vUv - 0.5;

    vec2 scaledUV = centeredUV * utextureSize;

    scaledUV += 0.5;

    scaledUV = clamp(scaledUV, 0.0, 1.0);

    gl_FragColor = texture2D(uTexture, scaledUV);
}

  `
);
extend({ FrameMaterial });

export function Frame2({ image, frameSize, thickness }) {
  const { nodes } = useGLTF("/3d/frame2.glb");
  const texture = useTexture(image);
  const materialRef = useRef();

  function calculatePosition(imageHeight, depth) {
    // Constants derived from observation
    const a = 0.15; // Adjust this based on regression/approximation
    const b = -0.5; // Adjust this based on regression/approximation

    // Non-linear formula (example: logarithmic relationship)
    return a * Math.log(imageHeight) + b;
  }
  // Example Usage:

  const centerWidth = frameSize.width - parseInt(thickness) * 2;
  const centerHeight = frameSize.height - parseInt(thickness) * 2;

  const [aspectX, aspectY] = [centerHeight, centerWidth];

  const sizeMapping = {
    //"5000X4000"
  };

  const textureSize = [1, 1];
  const customThickness = 2;

  const baseSize = 2.5;
  const scaleX = (aspectX / Math.max(aspectX, aspectY)) * baseSize;
  const scaleY = (aspectY / Math.max(aspectX, aspectY)) * baseSize;

  useEffect(() => {
    if (materialRef.current) {
      materialRef.current.uniforms.uTexture.value = texture;
      materialRef.current.uniforms.uFrameSize.value.set(aspectX, aspectY);
      const [x, y] = textureSize;
      materialRef.current.uniforms.utextureSize.value.set(x, y);
    }
  }, [texture, aspectX, aspectY, textureSize]);

  return (
    <group>
      <group
        dispose={null}
        scale={[scaleX, customThickness, scaleY]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
      >
        <mesh geometry={nodes.Plane.geometry}>
          <frameMaterial
            ref={materialRef}
            key={FrameMaterial.key}
            side={THREE.DoubleSide}
          />
        </mesh>
        <mesh
          geometry={nodes.Plane001.geometry}
          material={nodes.Plane001.material}
        >
          <meshStandardMaterial
            roughness={0.9}
            color="#826a42"
            side={THREE.DoubleSide}
          />
        </mesh>
        <mesh
          geometry={nodes.Object_2001.geometry}
          material={nodes.Object_2001.material}
          position={[-0.915, -0.126, -0.016]}
          rotation={[-1.56, -1.243, 0.004]}
          scale={0.203}
        >
          <meshStandardMaterial metalness={1.0} roughness={0.2} />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/3d/frame2.glb");
